export const navLinks = [
  {
    id: 1,
    name: "Home",
    href: "/",
  },
  {
    id: 2,
    name: "create",
    href: "/create",
  },
  {
    id: 3,
    name: "notification",
    href: "/notification",
  },
  {
    id: 4,
    name: "messages",
    href: "/messages",
  },
];

export const posts = [
  {
    id: "1",
    title: "Morning Sunrise",
    description: "This is the description for post 1",
    image: "/images/pic (1).jpg",
    name: "Ava Morales",
    avatar: "/images/user (1).jpg",
    links: ["https://example.com/download/post1"],
    downloadUrl: "https://example.com/download/post1",
    likes: 100,
    followers: 100,
    tags: ["Nature", "Sunrise", "Photography", "Morning", "Happy"],
  },
  {
    id: "2",
    title: "Evening Breeze",
    description: "This is the description for post 2",
    image: "/images/pic (2).jpg",
    name: "Hannah Kim",
    avatar: "/images/user (2).jpg",
    links: ["https://example.com/download/post2"],
    downloadUrl: "https://example.com/download/post2",
    likes: 200,
    followers: 1500000,
    tags: ["Nature", "Sunset", "Peaceful", "Evening", "Happy"],
  },
  {
    id: "3",
    title: "Midnight Dreams",
    description: "This is the description for post 3",
    image: "/images/pic (3).jpg",
    name: "Julian Sanchez",
    avatar: "/images/user (3).jpg",
    links: ["https://example.com/download/post3"],
    downloadUrl: "https://example.com/download/post3",
    likes: 300,
    followers: 2000,
    tags: ["Night", "Stars", "Dreamy", "Midnight", "Happy"],
  },
  {
    id: "4",
    title: "Afternoon Delight",
    description: "This is the description for post 4",
    image: "/images/pic (4).jpg",
    name: "Sophia Rodriguez",
    avatar: "/images/user (4).jpg",
    links: ["https://example.com/download/post4"],
    downloadUrl: "https://example.com/download/post4",
    likes: 400,
    followers: 25000,
    tags: ["Nature", "Afternoon", "Sunny", "Afternoon", "Happy"],
  },
  {
    id: "5",
    title: "Sunset Serenade",
    description: "This is the description for post 5",
    image: "/images/pic (5).jpg",
    name: "Noah White",
    avatar: "/images/user (5).jpg",
    links: [
      "https://example.com/download/post5",
      "https://abc.com/download/post5",
      "https://zdvfdfdv.com/download/post5",
    ],
    downloadUrl: "https://example.com/download/post5",
    likes: 500,
    followers: 12000000,
    tags: ["Nature", "Sunset", "Music", "Sunset", "Happy"],
  },
  {
    id: "6",
    title: "Dawn Awakening",
    description: "This is the description for post 6",
    image: "/images/pic (6).jpg",
    name: "Lily Brown",
    avatar: "/images/user (6).jpg",
    links: ["https://example.com/download/post6"],
    downloadUrl: "https://example.com/download/post6",
    likes: 600,
    followers: 3500,
    tags: ["Nature", "Dawn", "NewBeginnings", "Dawn", "Happy"],
  },
  {
    id: "7",
    title: "Nighttime Whispers",
    description: "This is the description for post 7",
    image: "/images/pic (7).jpg",
    name: "Ethan Hall",
    avatar: "/images/user (7).jpg",
    links: ["https://example.com/download/post7"],
    downloadUrl: "https://example.com/download/post7",
    likes: 700,
    followers: 4000,
    tags: ["Night", "Whispers", "Mystery", "Night", "Happy"],
  },
  {
    id: "8",
    title: "Morning Dew",
    description: "This is the description for post 8",
    image: "/images/pic (8).jpg",
    name: "Emily Davis",
    avatar: "/images/user (8).jpg",
    links: ["https://example.com/download/post8"],
    downloadUrl: "https://example.com/download/post8",
    likes: 800,
    followers: 4500,
    tags: ["Nature", "Morning", "Dew", "Morning", "Happy"],
  },
  {
    id: "9",
    title: "Evening Shadows",
    description: "This is the description for post 9",
    image: "/images/pic (9).jpg",
    name: "Oliver Martin",
    avatar: "/images/user (9).jpg",
    links: ["https://example.com/download/post9"],
    downloadUrl: "https://example.com/download/post9",
    likes: 900,
    followers: 5000,
    tags: ["Nature", "Evening", "Shadows", "Evening", "Happy"],
  },
  {
    id: "10",
    title: "Midday Reflections",
    description: "This is the description for post 10",
    image: "/images/pic (10).jpg",
    name: "Isabella Taylor",
    avatar: "/images/user (10).jpg",
    links: ["https://example.com/download/post10"],
    downloadUrl: "https://example.com/download/post10",
    likes: 1000,
    followers: 5500,
    tags: ["Nature", "Midday", "Reflections", "Midday", "Happy"],
  },
  {
    id: "11",
    title: "Afternoon Haze",
    description: "This is the description for post 11",
    image: "/images/pic (11).jpg",
    name: "Alexander Lee",
    avatar: "/images/user (11).jpg",
    links: ["https://example.com/download/post11"],
    downloadUrl: "https://example.com/download/post11",
    likes: 1100,
    followers: 6000,
    tags: ["Nature", "Afternoon", "Haze", "Afternoon", "Happy"],
  },
  {
    id: "12",
    title: "Sunset Glow",
    description: "This is the description for post 12",
    image: "/images/pic (12).jpg",
    name: "Gabriella Garcia",
    avatar: "/images/user (12).jpg",
    links: ["https://example.com/download/post12"],
    downloadUrl: "https://example.com/download/post12",
    likes: 1200,
    followers: 6500,
    tags: ["Nature", "Sunset", "Glow", "Sunset", "Happy"],
  },
  {
    id: "13",
    title: "Dawn's Early Light",
    description: "This is the description for post 13",
    image: "/images/pic (13).jpg",
    name: "Michael Patel",
    avatar: "/images/user (13).jpg",
    links: ["https://example.com/download/post13"],
    downloadUrl: "https://example.com/download/post13",
    likes: 1300,
    followers: 7000,
    tags: ["Nature", "Dawn", "EarlyLight", "Dawn", "Happy"],
  },
  {
    id: "14",
    title: "Night's Soft Silence",
    description: "This is the description for post 14",
    image: "/images/pic (14).jpg",
    name: "Samantha Brown",
    avatar: "/images/user (14).jpg",
    links: ["https://example.com/download/post14"],
    downloadUrl: "https://example.com/download/post14",
    likes: 1400,
    followers: 7500,
    tags: ["Nature", "Night", "Silence", "Night", "Happy"],
  },
  {
    id: "15",
    title: "Morning's Golden Hour",
    description: "This is the description for post 15",
    image: "/images/pic (15).jpg",
    name: "Benjamin Thompson",
    avatar: "/images/user (15).jpg",
    links: ["https://example.com/download/post15"],
    downloadUrl: "https://example.com/download/post15",
    likes: 1500,
    followers: 800,
    tags: ["Nature", "Morning", "GoldenHour", "Morning", "Happy"],
  },
  {
    id: "16",
    title: "Evening's Warmth",
    description: "This is the description for post 16",
    image: "/images/pic (16).jpg",
    name: "Charlotte Jackson",
    avatar: "/images/user (16).jpg",
    links: ["https://example.com/download/post16"],
    downloadUrl: "https://example.com/download/post16",
    likes: 1600,
    followers: 8500,
    tags: ["Nature", "Evening", "Warmth", "Evening", "Happy"],
  },
  {
    id: "17",
    title: "Midnight's Starry Sky",
    description: "This is the description for post 17",
    image: "/images/pic (17).jpg",
    name: "Ethan Walker",
    avatar: "/images/user (17).jpg",
    links: ["https://example.com/download/post17"],
    downloadUrl: "https://example.com/download/post17",
    likes: 1700,
    followers: 9000,
    tags: ["Nature", "Night", "StarrySky", "Night", "Happy"],
  },
  {
    id: "18",
    title: "Sunrise Serenity",
    description: "This is the description for post 18",
    image: "/images/pic (18).jpg",
    name: "Olivia Martin",
    avatar: "/images/user (18).jpg",
    links: ["https://example.com/download/post18"],
    downloadUrl: "https://example.com/download/post18",
    likes: 1800,
    followers: 9500,
    tags: ["Nature", "Sunrise", "Serenity", "Sunrise", "Happy"],
  },
  {
    id: "19",
    title: "Noon's Vibrant Energy",
    description: "This is the description for post 19",
    image: "/images/pic (19).jpg",
    name: "Alexander Brooks",
    avatar: "/images/user (19).jpg",
    links: ["https://example.com/download/post19"],
    downloadUrl: "https://example.com/download/post19",
    likes: 1900,
    followers: 10000,
    tags: ["Nature", "Noon", "VibrantEnergy", "Noon", "Happy"],
  },
  {
    id: "20",
    title: "Twilight's Soft Glow",
    description: "This is the description for post 20",
    image: "/images/pic (20).jpg",
    name: "Hannah Kim",
    avatar: "/images/user (20).jpg",
    links: ["https://example.com/download/post20"],
    downloadUrl: "https://example.com/download/post20",
    likes: 2000,
    followers: 10500,
    tags: ["Nature", "Twilight", "SoftGlow", "Twilight", "Happy"],
  },
];

export const users = [
  {
    id: "1",
    name: "Ava Morales",
    username: "ava_morales",
    avatar: "/images/user (1).jpg",
    banner: "/images/pic (1).jpg",
    bio: "Nature enthusiast and photographer capturing life's beauty through lenses. Exploring the world and sharing the wonders of nature.",
    followers: ["hannah_kim", "julian_sanchez", "sophia_rodriguez"],
    following: ["julian_sanchez", "sophia_rodriguez", "noah_white"],
    posts: ["1", "2", "3"],
    saved: ["4", "5", "6"],
  },
  {
    id: "2",
    name: "Hannah Kim",
    username: "hannah_kim",
    avatar: "/images/user (2).jpg",
    banner: "/images/pic (2).jpg",
    bio: "Traveling foodie exploring flavors and cultures worldwide. Sharing the joy of food and travel.",
    followers: ["ava_morales", "julian_sanchez", "sophia_rodriguez"],
    following: ["ava_morales", "julian_sanchez", "sophia_rodriguez"],
    posts: ["7", "8", "9"],
    saved: ["10", "11", "12"],
  },
  {
    id: "3",
    name: "Julian Sanchez",
    username: "julian_sanchez",
    avatar: "/images/user (3).jpg",
    banner: "/images/pic (3).jpg",
    bio: "Fitness enthusiast and gamer pushing limits and exploring new worlds. Sharing the journey of fitness and gaming.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["13", "14", "15"],
    saved: ["16", "17", "18"],
  },
  {
    id: "4",
    name: "Sophia Rodriguez",
    username: "sophia_rodriguez",
    avatar: "/images/user (4).jpg",
    banner: "/images/pic (4).jpg",
    bio: "Fashion designer and artist creating beauty through textiles and art. Sharing the world of fashion and art.",
    followers: ["ava_morales", "hannah_kim", "julian_sanchez"],
    following: ["ava_morales", "hannah_kim", "julian_sanchez"],
    posts: ["19", "20", "1"],
    saved: ["2", "3", "4"],
  },
  {
    id: "5",
    name: "Noah White",
    username: "noah_white",
    avatar: "/images/user (5).jpg",
    banner:
      "https://vjkurbrp7v9schki.public.blob.vercel-storage.com/(Edited%20images)-MLPTJSTSHEn5v87FlUEgEsOuLU0yU2.jpg",
    bio: "🎵📝 I'm Noah White, a musician and writer. My music explores love, nature, and self-discovery. I've published poetry collections and am working on my debut novel, inspired by my love for the outdoors and passion for storytelling. 📝🎵",
    followers: ["ava_morales", "julian_sanchez", "sophia_rodriguez"],
    following: ["ava_morales", "julian_sanchez", "sophia_rodriguez"],
    posts: ["5", "6", "7"],
    saved: ["8", "9", "10"],
  },
  {
    id: "6",
    name: "Lily Brown",
    username: "lily_brown",
    avatar: "/images/user (6).jpg",
    banner: "", // Left banner empty
    bio: "Yoga instructor and wellness advocate promoting balance and harmony. Sharing the world of yoga and wellness.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["11", "12", "13"],
    saved: ["14", "15", "16"],
  },
  {
    id: "7",
    name: "Ethan Hall",
    username: "ethan_hall",
    avatar: "/images/user (7).jpg",
    banner: "/images/pic (7).jpg",
    bio: "Tech enthusiast and entrepreneur driving innovation and progress. Sharing the world of tech and entrepreneurship.",
    followers: ["ava_morales", "julian_sanchez", "noah_white"],
    following: ["ava_morales", "julian_sanchez", "noah_white"],
    posts: ["17", "18", "19"],
    saved: ["1", "2", "3"],
  },
  {
    id: "8",
    name: "Emily Davis",
    username: "emily_davis",
    avatar: "/images/user (8).jpg",
    banner: "/images/pic (8).jpg",
    bio: "Teacher and book lover inspiring minds and fostering knowledge. Sharing the world of teaching and books.",
    followers: ["hannah_kim", "sophia_rodriguez", "lily_brown"],
    following: ["hannah_kim", "sophia_rodriguez", "lily_brown"],
    posts: ["4", "5", "6"],
    saved: ["7", "8", "9"],
  },
  {
    id: "9",
    name: "Oliver Martin",
    username: "oliver_martin",
    avatar: "/images/user (9).jpg",
    banner: "/images/pic (9).jpg",
    bio: "Engineer and outdoor enthusiast pushing boundaries and exploring nature. Sharing the world of engineering and nature.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["10", "11", "12"],
    saved: ["13", "14", "15"],
  },
  {
    id: "10",
    name: "Isabella Taylor",
    username: "isabella_taylor",
    avatar: "/images/user (10).jpg",
    banner: "",
    bio: "Dancer and choreographer expressing emotions through movement and art. Sharing the world of dance and choreography.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["14", "15", "16"],
    saved: ["17", "18", "19"],
  },
  {
    id: "11",
    name: "Alexander Lee",
    username: "alexander_lee",
    avatar: "/images/user (11).jpg",
    banner: "/images/pic (11).jpg",
    bio: "Chef and food critic exploring flavors and culinary arts. Sharing the world of food and culinary arts.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["1", "2", "3"],
    saved: ["4", "5", "6"],
  },
  {
    id: "12",
    name: "Gabriella Garcia",
    username: "gabriella_garcia",
    avatar: "/images/user (12).jpg",
    banner: "/images/pic (12).jpg",
    bio: "Artist and graphic designer creating visual stories and experiences. Sharing the world of art and design.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["7", "8", "9"],
    saved: ["10", "11", "12"],
  },
  {
    id: "13",
    name: "Michael Patel",
    username: "michael_patel",
    avatar: "/images/user (13).jpg",
    banner: "",
    bio: "Doctor and medical researcher advancing healthcare and saving lives. Sharing the world of medicine and research.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["13", "14", "15"],
    saved: ["16", "17", "18"],
  },
  {
    id: "14",
    name: "Samantha Brown",
    username: "samantha_brown",
    avatar: "/images/user (14).jpg",
    banner: "/images/pic (14).jpg",
    bio: "Lawyer and social activist fighting for justice and equality. Sharing the world of law and social activism.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["19", "20", "1"],
    saved: ["2", "3", "4"],
  },
  {
    id: "15",
    name: "Benjamin Thompson",
    username: "benjamin_thompson",
    avatar: "/images/user (15).jpg",
    banner: "", // Left banner empty
    bio: "Software engineer and tech blogger driving innovation and progress. Sharing the world of software engineering and tech blogging.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["5", "6", "7"],
    saved: ["8", "9", "10"],
  },
  {
    id: "16",
    name: "Charlotte Jackson",
    username: "charlotte_jackson",
    avatar: "/images/user (16).jpg",
    banner: "/images/pic (16).jpg",
    bio: "Fashion model and influencer inspiring beauty and confidence. Sharing the world of fashion and modeling.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["11", "12", "13"],
    saved: ["14", "15", "16"],
  },
  {
    id: "17",
    name: "Ethan Walker",
    username: "ethan_walker",
    avatar: "/images/user (17).jpg",
    banner: "",
    bio: "Music producer and DJ creating sonic experiences and emotions. Sharing the world of music and DJing.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["17", "18", "19"],
    saved: ["1", "2", "3"],
  },
  {
    id: "18",
    name: "Olivia Martin",
    username: "olivia_martin",
    avatar: "/images/user (18).jpg",
    banner: "/images/pic (18).jpg",
    bio: "Yoga instructor and wellness coach promoting balance and harmony. Sharing the world of yoga and wellness.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["4", "5", "6"],
    saved: ["7", "8", "9"],
  },
  {
    id: "19",
    name: "Alexander Brooks",
    username: "alexander_brooks",
    avatar: "/images/user (19).jpg",
    banner: "",
    bio: "Engineer and robotics enthusiast pushing boundaries and innovation. Sharing the world of engineering and robotics.",
    followers: ["julian_sanchez", "noah_white", "ethan_hall"],
    following: ["julian_sanchez", "noah_white", "ethan_hall"],
    posts: ["10", "11", "12"],
    saved: ["13", "14", "15"],
  },
  {
    id: "20",
    name: "Gabriella Rodriguez",
    username: "gabriella_rodriguez",
    avatar: "/images/user (20).jpg",
    banner: "/images/pic (20).jpg",
    bio: "Artist and graphic designer creating visual stories and experiences. Sharing the world of art and design.",
    followers: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    following: ["ava_morales", "hannah_kim", "sophia_rodriguez"],
    posts: ["16", "17", "18"],
    saved: ["19", "20", "1"],
  },
];
